# docker compose --profile prod down && docker compose --profile prod up -d
# docker logs -f nextjs-prod
services:
  nextjs-prod:
    image: mdzenos/nextjs-core:1.1
    container_name: nextjs-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod

  nextjs-dev:
    image: node:24-slim
    container_name: nextjs-dev
    working_dir: /app
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    profiles:
      - dev
